language: python
python:
    - '2.7'
    - 'pypy'
    - '3.5'
    - '3.5-dev'
    - '3.6'
    - '3.6-dev'
    - '3.7-dev'
    - 'nightly'
    - 'pypy3'
env:
    - DJANGO_VERSION=1.5.10
    - DJANGO_VERSION=1.6.11
    - DJANGO_VERSION=1.7
    - DJANGO_VERSION=1.8
    - DJANGO_VERSION=1.9
    - DJANGO_VERSION=1.10
install:
    - pip install django==$DJANGO_VERSION
    - pip install gevent
    - python setup.py -q install
script:
    - python runtests.py
services:
    - postgresql
before_script:
    - psql -c 'create database test;' -U postgres
