language: python
python:
    - '2.7'
env:
    - DJANGO_VERSION=1.5.10
    - DJANGO_VERSION=1.6.7
    - DJANGO_VERSION=1.7
install:
    - pip install . --use-mirrors
    - pip install django==$DJANGO_VERSION
    - pip install psycopg2
    - python setup.py -q install
script:
    - python runtests.py
services:
    - postgresql
before_script:
    - psql -c 'create database test;' -U postgres
